change qrs and pets view
jOR13/hoppas pull request #1
Opened 2022-01-21 18:00 UTC by jOR13

views are  not finished yet (working on it)

@itsmeurbi

2022-01-21 23:08 UTC, itsmeurbi requested changes
I'm a bit out of context on what your application does.
Does it needs to handle json requests? If not, let's get rid of `format.json` blocks

2022-01-21 23:08 UTC, itsmeurbi commented on app/controllers/qrs_controller.rb
> +  def public
Your actions should only be `new`, `create`, `update`, `delete` or `new`

2022-01-21 23:08 UTC, itsmeurbi commented on app/services/qr_generator.rb
> +        puts "Generating QR code for #{@path}"
Is there a reason why you need this?

2022-01-22 23:01 UTC, itsmeurbi requested changes
Ok now this PR is HUGE!
Split it into small PRs so we can review it.

2022-01-24 23:16 UTC, merged

2022-01-24 23:18 UTC, itsmeurbi commented
@jOR13 why did we merge this without any approval? 🚨

2022-01-26 20:27 UTC, jOR13 commented on app/views/pets/index.html.erb
> +  <div class="columns is-multiline" id="pets" style="justify-content: center;">
already fix it

2022-01-26 20:27 UTC, jOR13 commented on app/views/pets/index.html.erb
> +    <div class="card"  style="min-height: 230px; min-width: 180px; min-height: 400px; border-radius: 20px;">
already fix it

2022-01-26 20:27 UTC, jOR13 commented on app/views/pets/index.html.erb
> +          <%= image_tag url_for(pet.image.variant(resize_to_fit: [200, 200])),
already fix it

2022-01-26 20:27 UTC, jOR13 commented on app/views/pets/index.html.erb
> +          style: 'border-top-right-radius: 20px;
already fix it

2022-01-26 20:27 UTC, jOR13 commented on app/views/qrs/_qr.html.erb
> +        <%# <%= image_tag url_for(qr.pet.image.variant(resize_to_fill: [200, 200])), class: "image is-64x64", style: "border-radius: 40px; display: flex;"%>
already fix it

2022-01-26 20:28 UTC, jOR13 commented on app/views/qrs/index.html.erb
> +    <div>
already fix it

2022-01-26 20:28 UTC, jOR13 commented on app/controllers/qrs_controller.rb
> +  def public
already fix it i have a better idea how routes it works

2022-01-26 20:29 UTC, jOR13 commented on app/services/qr_generator.rb
> +        puts "Generating QR code for #{@path}"
na that was just for test the output, but i delete it